import { SidebarConfig } from "@docusaurus/plugin-content-docs/src/sidebars/types.js";
import topics from "./src";

const sidebars: SidebarConfig = Object.fromEntries(
  topics.map(
    ({ slug }) => [slug, [{ type: "autogenerated", dirName: slug }]] as const
  )
);

export default sidebars;
