// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  nipple: [{type: 'autogenerated', dirName: 'nipple'}],
  prostate: [{type: 'autogenerated', dirName: 'prostate'}],
  hypnosis: [{type: 'autogenerated', dirName: 'hypnosis'}],
};

module.exports = sidebars;
